version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - yum update && um upgrade -y
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install terraform
      - terraform version
  build:
    commands:
      - echo Build started on `date`
      - cd env/dev
      - terraform init
      - terraform plan