version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - suddo yum update && sudo yum upgrade -y
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - terraform version
  build:
    commands:
      - echo Build started on `date`
      - cd env/dev
      - terraform init
      - terraform apply